### ISSUE TITLE
Implement Clone for Data/Record

### ISSUE THREAD

**Issue by mcdenhoed** [The6P4C/srec#1]
Hello! This is a great library! Thanks for publishing!

Would you consider implementing `Clone` for `Data`/`Record`? I tried using this library to perform some edits on some SRECs and kept running into situations where I wanted to be a be able to just clone a Record object. Since all the `Address` structs and `Vec` implement `Clone` it shouldn't be too bad to add.

**Comment by the6p4c** [comment]
Hi! I can't see how adding `Clone` would be a breaking change, so I'll try and get this done and bump the minor version as soon as I can.

**Comment by the6p4c** [comment]
Added in a819084, published as v0.1.2 :)

**Comment by mcdenhoed** [comment]
That is awesome, thank you!
